---
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-load-test
  namespace: sample-workloads
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command:
          - /bin/sh
          - -c
          - |
            for i in $(seq 1 1000); do
              curl -s http://nginx-sample.sample-workloads.svc.cluster.local/ > /dev/null
              sleep 0.1
            done
      restartPolicy: Never
  backoffLimit: 2
