---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: sample-workloads
  labels:
    app: stress-test
    type: cpu
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
      - "--cpu"
      - "2"
      - "--timeout"
      - "300s"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
  namespace: sample-workloads
  labels:
    app: stress-test
    type: memory
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "200M"
      - "--timeout"
      - "300s"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Never
